spring.application.name=MiPeluqueriaVirtual

# Base de datos
server.port=${PORT:8080}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT y Google
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
google.client.id=125503893410-s6re2cklka3938pm569jh1c94kvfr7fi.apps.googleusercontent.com

# Correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true